[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
voting_dapp = "7d29uc72C7kteN9mnrjDbLdqDN8qQX1dbcJHZRB91s8Q"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
